### PR TITLE
Get test suite fully passing by fixing failing `MultistreamTests.testBasic` assertion

### PR DESCRIPTION
**Pull request by tsheaff**
Results from test suite on `master`:

Screen Shot 2021-09-22 at 9 11 29 PM

Results on this branch after the fix:

Screen Shot 2021-09-22 at 9 09 39 PM

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks Tyler! We'll get a review on this soon.

Sent you a welcome message on https://github.com/lbryio/odysee-ios/pull/245#issuecomment-925883775, same would apply to other PRs.

**Comment by tsheaff** [comment]
@tzarebczan @akinwale once this merges and test suite is passing, it would be nice to avoid any merges going forward that don't pass the test suite. Thoughts on how to configure this step? We could use Github Workflows, CircleCI, Travis etc. I see y'all are using Travis for CI on some of the other repos but not this one. Thoughts?

**Comment by akinwale** [comment]
@tsheaff I'm not very familiar with CI options for macOS / iOS builds, so I cannot comment on this at the moment. I'll do some research and try to provide feedback later on.

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
