### PR TITLE
Enforce SwiftFormat across the codebase

### PR DESCRIPTION
**Pull request by tsheaff**
## Rationale

Formatters are an excellent way to support developer velocity as more contributors are active in a codebase. Some advantages:

* Avoid parts of the code feeling super different style-wise from other parts, giving the whole codebase a consistent feel, which drastically improves readability
* Avoid [bikeshedding](https://thedecisionlab.com/biases/bikeshedding/) about low-level style questions, leaving PR comments and dev time spent on adding user value
* Automatically fix certain types of common mistakes

## Why SwiftFormat?

The most full-featured and well-adopted swift formatter is [SwiftFormat](https://github.com/nicklockwood/SwiftFormat). It's very configurable (see rules [here](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md)) but comes with a nice set of defaults. I've used it in other projects I've worked on, and everyone seemed to really like it.

## Approach

This PR does the following:

1. Set up SwiftFormat in the codebase using [Mint](https://github.com/yonaskolb/Mint) as the package manager
2. Run `swiftformat .` to enforce the style across the codebase. This is where ~99% of this diff comes from, and was all done automatically with that one command.
3. Enforce that `SwiftFormat` always pass before merging to `master` using [GitHub Workflows](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions). Once this PR merges, this can be enforced on the `master` branch by a repo admin under Settings > Branches, guaranteeing that everything on `master` always formats properly
4. Add installation instructions for `SwiftFormat` in the `README.md` so that devs can run it locally.

I'm super open to tweaking the `.swiftformat` configuration if the team feels some of the defaults or the few overrides I proposed aren't ergonomic for this codebase.

## Rollout

If there are any outstanding branches that have not yet merged before this does, the process to avoid conflicts is very simple:

* Merge `master` back to your branch after this merges.
* If there are any conflicts, checkout *ours* to take your changes
* Simply rerun `swiftformat .` locally to get the formatter passing once again.
* When ready, PR your branch back to `master`

### CODE REVIEW

**Comment by eclectocrat** [comment]
Just want to comment: heck yes! I love code formatters, they remove stress and make things much easier to read and maintain. 👍

**Comment by tzarebczan** [comment]
Hey @tsheaff, thanks so much for working on this awesome improvement, and congrats on the first PR! 

We'll get a review on it soon.

Can we show you some [appreciation](https://lbry.com/faq/appreciation)?

**Comment by tsheaff** [comment]
Thanks @tzarebczan I just sent an email for any appreciation 🎩

Once this merges, a repo admin should make the formatter a blocking step for merges on the `master` branch.

**Comment by akinwale** [comment]
This is great stuff, thanks! It's always nice to see developments like this. I will review this in a bit.

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Comment by tsheaff** [comment]
Thanks @akinwale !

@akinwale can you enforce the `lint` job to be a required step before merging under the repo's `Settings > Branches > master` settings?

**Pull request merged**
